//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAttendance
    {
        public System.Guid Id { get; set; }
        public System.Guid CourseId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool Attendance { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
