//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public System.Guid Id { get; set; }
        public int CanvasId { get; set; }
        public System.Guid RoomId { get; set; }
        public bool IsOnSunday { get; set; }
        public bool IsOnMonday { get; set; }
        public bool IsOnTuesday { get; set; }
        public bool IsOnWednesday { get; set; }
        public bool IsOnThursday { get; set; }
        public bool IsOnFriday { get; set; }
        public bool IsOnSaturday { get; set; }
        public int StartTime { get; set; }
        public int StopTime { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
