//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseAttendances = new HashSet<CourseAttendance>();
            this.CourseOwners = new HashSet<CourseOwner>();
            this.CourseStudents = new HashSet<CourseStudent>();
        }
    
        public System.Guid Id { get; set; }
        public string CourseCode { get; set; }
        public string CourseNumber { get; set; }
        public int CourseSection { get; set; }
        public string CourseName { get; set; }
        public int ClassNumber { get; set; }
        public bool IsActive { get; set; }
        public bool IsOnSunday { get; set; }
        public bool IsOnMonday { get; set; }
        public bool IsOnTuesday { get; set; }
        public bool IsOnWednesday { get; set; }
        public bool IsOnThursday { get; set; }
        public bool IsOnFriday { get; set; }
        public bool IsOnSaturday { get; set; }
        public int StartTime { get; set; }
        public int StopTime { get; set; }
        public string Semester { get; set; }
        public int Year { get; set; }
        public System.Guid LocationRoomId { get; set; }
        public string ActiveAttendanceCode { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<CourseAttendance> CourseAttendances { get; set; }
        public virtual ICollection<CourseOwner> CourseOwners { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
    }
}
